#TODO: Add the .env file for saving aws cred, and jwt secret
spring.application.name=backend
server.port=8092

skip.tests=true

#IP address of linux hosting Postgresql is removed for GitHub push
spring.datasource.url=jdbc:postgresql://<Linux-IP>:5432/mtracker_database
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database=POSTGRESQL
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
logging.level.org.springframework.web=debug
logging.level.org.hibernate=debug
spring.jpa.generate-ddl=true

#JWT secret removed for GitHub push
jwt.secret=demo
jwt.expiration=3600000

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
project.image=C:/Users/savit/OneDrive/Desktop/MTracker/images/
aws.image=""
project.migrated=false

#AWS information is removed for GitHub push
